name: Tests

on:
  push:

jobs:
  test:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        cache: false
        architecture: x64
        go-version: stable

    - name: Run go vet
      run: go vet ./...

    # no tests to run
    # - name: Run tests
    # run: go test -count 1 -v -timeout 1m ./...
